const fs = require('fs');
const path = require('path');

const REPOWIKI_DIR = path.join(__dirname, '../repowiki');
const TARGET_DOCS_DIR = path.join(__dirname, 'docs');
const TARGET_DOCS_ZH_DIR = path.join(__dirname, 'docs-zh');

// Setup
fs.rmSync(TARGET_DOCS_DIR, { recursive: true, force: true });
fs.rmSync(TARGET_DOCS_ZH_DIR, { recursive: true, force: true });
fs.mkdirSync(TARGET_DOCS_DIR, { recursive: true });
fs.mkdirSync(TARGET_DOCS_ZH_DIR, { recursive: true });

function sanitizeMarkdown(content) {
  // 1. Remove <cite> reference blocks completely (with or without closing tag)
  content = content.replace(/<cite>[\s\S]*?<\/cite>/g, '');
  content = content.replace(/&lt;cite&gt;[\s\S]*?&lt;\/cite&gt;/g, '');
  // Handle unclosed <cite> blocks (match until double newline)
  content = content.replace(/<cite>[\s\S]*?\n\n/g, '\n');
  content = content.replace(/&lt;cite&gt;[\s\S]*?\n\n/g, '\n');

  // Split by code blocks (fenced and inline) to avoid touching tags inside code/mermaid blocks
  const parts = content.split(/(```[\s\S]*?```|~~~[\s\S]*?~~~|`[^`]*`)/);
  // Allowed valid HTML tags that MDX can safely parse
  const allowedTagsRegex = /<(?!(\/?(br|hr|div|span|img|a|p|table|tr|td|th|thead|tbody|ul|li|ol|h1|h2|h3|h4|h5|h6|b|i|strong|em|pre|blockquote|details|summary)(\s|>|\/)))/gi;

  for (let i = 0; i < parts.length; i++) {
    if (i % 2 === 0) {
      parts[i] = parts[i].replace(/\{/g, '&#123;').replace(/\}/g, '&#125;');
      parts[i] = parts[i].replace(allowedTagsRegex, '&lt;');
      parts[i] = parts[i].replace(/&lt;([a-zA-Z0-9_\-]+)>/g, '&lt;$1&gt;');
      parts[i] = parts[i].replace(/&lt;\/([a-zA-Z0-9_\-]+)>/g, '&lt;/$1&gt;');
    }
  }
  return parts.join('');
}

function processDirectory(sourceDir, targetDir) {
  if (!fs.existsSync(sourceDir)) return;
  const entries = fs.readdirSync(sourceDir, { withFileTypes: true });
  for (const entry of entries) {
    const srcPath = path.join(sourceDir, entry.name);
    const destPath = path.join(targetDir, entry.name);
    if (entry.isDirectory()) {
      fs.mkdirSync(destPath, { recursive: true });
      processDirectory(srcPath, destPath);
    } else if (entry.isFile() && entry.name.endsWith('.md')) {
      const content = fs.readFileSync(srcPath, 'utf-8');
      fs.writeFileSync(destPath, sanitizeMarkdown(content));
    } else if (entry.isFile()) {
      fs.copyFileSync(srcPath, destPath);
    }
  }
}

function getOrderFromMetadata(metadataPath) {
  if (!fs.existsSync(metadataPath)) return {};
  const metadata = JSON.parse(fs.readFileSync(metadataPath, 'utf-8'));
  const orderMap = {};
  let pos = 1;
  const catalogs = metadata.wiki_catalogs || [];
  
  for (const cat of catalogs) {
    // Only top-level items determine the base sidebar ordering for directories/files
    if (!cat.parent_id) {
      orderMap[cat.name] = pos;
      // Also map with .md suffix in case it's a standalone file
      orderMap[cat.name + '.md'] = pos; 
      pos++;
    }
  }
  return orderMap;
}

const zhOrder = getOrderFromMetadata(path.join(REPOWIKI_DIR, 'zh/meta/repowiki-metadata.json'));
const enOrder = getOrderFromMetadata(path.join(REPOWIKI_DIR, 'en/meta/repowiki-metadata.json'));

function applySidebarOrder(targetDir, orderMap) {
  if (!fs.existsSync(targetDir)) return;
  const entries = fs.readdirSync(targetDir, { withFileTypes: true });
  for (const entry of entries) {
    const name = entry.name;
    const pos = orderMap[name];
    if (pos === undefined) continue;
    if (entry.isDirectory()) {
      const catFile = path.join(targetDir, name, '_category_.json');
      fs.writeFileSync(catFile, JSON.stringify({ label: name, position: pos }, null, 2));
    } else if (entry.isFile() && name.endsWith('.md')) {
      const filePath = path.join(targetDir, name);
      let content = fs.readFileSync(filePath, 'utf-8');
      if (content.startsWith('---')) {
        content = content.replace(/^---/, `---\nsidebar_position: ${pos}`);
      } else {
        content = `---\nsidebar_position: ${pos}\n---\n\n${content}`;
      }
      fs.writeFileSync(filePath, content);
    }
  }
}

// 1. Copy and sanitize
processDirectory(path.join(REPOWIKI_DIR, 'en/content'), TARGET_DOCS_DIR);
processDirectory(path.join(REPOWIKI_DIR, 'zh/content'), TARGET_DOCS_ZH_DIR);

// 2. Apply sidebar ordering
applySidebarOrder(TARGET_DOCS_DIR, enOrder);
applySidebarOrder(TARGET_DOCS_ZH_DIR, zhOrder);

// 3. Generate sidebars
fs.writeFileSync(path.join(__dirname, 'sidebars.ts'), `\
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
const sidebars: SidebarsConfig = {
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
};
export default sidebars;
`);

fs.writeFileSync(path.join(__dirname, 'sidebars-zh.ts'), `\
import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
const sidebars: SidebarsConfig = {
  zhSidebar: [{type: 'autogenerated', dirName: '.'}],
};
export default sidebars;
`);

console.log('Sync and sanitization complete.');
